### ISSUE TITLE
general questions

### ISSUE THREAD

**Issue by aleloh** [lucordes/unibodysweep#2]
Sorry for the amateur questions.

Can I use a promicro on this pcb? Do I need to solder diodes? Which switch is compatible with this pcb?

thank you

**Comment by lucordes** [comment]
I would not recommend a pro micro. The keycaps are in the way of the cable. I would recommend a Nice nano v2 and charge it every few months.
Yes you need to solder on some diodes.
Only kailh low profile choc v1 is compatible.
Btw if you choose zmk for the firmware you can compile it via git hub actions like this (https://github.com/lucordes/zmk-config) or just build it locally like this (https://github.com/lucordes/zmk/tree/main/app/boards/shields/unibodysweep).
I hope this helps.

**Comment by aleloh** [comment]
ty
